# Generated by Django 5.2.8 on 2025-11-23 22:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SesionSimulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escenario_nombre', models.CharField(help_text='Nombre del escenario simulado', max_length=100)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de inicio de la sesión')),
                ('fecha_fin', models.DateTimeField(blank=True, help_text='Fecha y hora de fin de la sesión', null=True)),
                ('duracion_segundos', models.IntegerField(default=0, help_text='Duración total de la sesión en segundos', validators=[django.core.validators.MinValueValidator(0)])),
                ('completada', models.BooleanField(default=False, help_text='Indica si la sesión fue completada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_simulacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sesión de Simulación',
                'verbose_name_plural': 'Sesiones de Simulación',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='MetricaDesempeno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_estres', models.IntegerField(help_text='Nivel de estrés final (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('decisiones_acertadas', models.IntegerField(default=0, help_text='Cantidad de decisiones acertadas', validators=[django.core.validators.MinValueValidator(0)])),
                ('decisiones_totales', models.IntegerField(default=0, help_text='Cantidad total de decisiones tomadas', validators=[django.core.validators.MinValueValidator(0)])),
                ('tiempo_promedio_decision', models.IntegerField(default=0, help_text='Tiempo promedio de respuesta en segundos', validators=[django.core.validators.MinValueValidator(0)])),
                ('eventos_manejados', models.IntegerField(default=0, help_text='Cantidad de eventos manejados correctamente', validators=[django.core.validators.MinValueValidator(0)])),
                ('timestamp_captura', models.DateTimeField(auto_now_add=True, help_text='Momento en que se capturaron las métricas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sesion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metricas', to='pragma_dashboard.sesionsimulacion')),
            ],
            options={
                'verbose_name': 'Métrica de Desempeño',
                'verbose_name_plural': 'Métricas de Desempeño',
            },
        ),
        migrations.CreateModel(
            name='EventoOcurrido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento_id', models.CharField(help_text='Identificador único del evento', max_length=100)),
                ('timestamp_ocurrencia', models.DateTimeField(help_text='Momento en que ocurrió el evento')),
                ('fue_manejado_correctamente', models.BooleanField(help_text='Indica si el evento fue manejado correctamente')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='pragma_dashboard.sesionsimulacion')),
            ],
            options={
                'verbose_name': 'Evento Ocurrido',
                'verbose_name_plural': 'Eventos Ocurridos',
                'ordering': ['-timestamp_ocurrencia'],
            },
        ),
        migrations.CreateModel(
            name='DecisionTomada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_id', models.CharField(help_text='Identificador único de la decisión en el escenario', max_length=100)),
                ('tiempo_respuesta_segundos', models.IntegerField(help_text='Tiempo que tardó el usuario en responder', validators=[django.core.validators.MinValueValidator(0)])),
                ('fue_acertada', models.BooleanField(help_text='Indica si la decisión fue correcta')),
                ('timestamp_decision', models.DateTimeField(auto_now_add=True, help_text='Momento exacto en que se tomó la decisión')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisiones', to='pragma_dashboard.sesionsimulacion')),
            ],
            options={
                'verbose_name': 'Decisión Tomada',
                'verbose_name_plural': 'Decisiones Tomadas',
                'ordering': ['-timestamp_decision'],
            },
        ),
        migrations.CreateModel(
            name='ProgresoHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_calculo', models.DateField(auto_now_add=True, help_text='Fecha del cálculo de progreso')),
                ('promedio_estres', models.DecimalField(decimal_places=2, help_text='Promedio de estrés en escala 0-100', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('sesiones_completadas', models.IntegerField(default=0, help_text='Cantidad de sesiones completadas', validators=[django.core.validators.MinValueValidator(0)])),
                ('tiempo_total_minutos', models.IntegerField(default=0, help_text='Tiempo total invertido en minutos', validators=[django.core.validators.MinValueValidator(0)])),
                ('escenarios_practicados', models.CharField(blank=True, help_text='Lista de escenarios practicados', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progreso_historico', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progreso Histórico',
                'verbose_name_plural': 'Progresos Históricos',
                'ordering': ['-fecha_calculo'],
                'indexes': [models.Index(fields=['usuario', '-fecha_calculo'], name='pragma_dash_usuario_6b05e7_idx')],
            },
        ),
        migrations.CreateModel(
            name='SaveFileUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datos_savefile', models.TextField(help_text='Datos del archivo guardado en JSON o formato específico')),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True, help_text='Última fecha de actualización')),
                ('version_savefile', models.CharField(default='1.0', help_text='Versión del formato del savefile', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savefiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Archivo Guardado de Usuario',
                'verbose_name_plural': 'Archivos Guardados de Usuario',
                'ordering': ['-ultima_actualizacion'],
                'indexes': [models.Index(fields=['usuario', '-ultima_actualizacion'], name='pragma_dash_usuario_b60172_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='sesionsimulacion',
            index=models.Index(fields=['usuario', '-fecha_inicio'], name='pragma_dash_usuario_f7022c_idx'),
        ),
        migrations.AddIndex(
            model_name='sesionsimulacion',
            index=models.Index(fields=['completada'], name='pragma_dash_complet_d45b4b_idx'),
        ),
        migrations.AddIndex(
            model_name='eventoocurrido',
            index=models.Index(fields=['sesion', '-timestamp_ocurrencia'], name='pragma_dash_sesion__127e44_idx'),
        ),
        migrations.AddIndex(
            model_name='eventoocurrido',
            index=models.Index(fields=['fue_manejado_correctamente'], name='pragma_dash_fue_man_db6ae1_idx'),
        ),
        migrations.AddIndex(
            model_name='decisiontomada',
            index=models.Index(fields=['sesion', '-timestamp_decision'], name='pragma_dash_sesion__febbdd_idx'),
        ),
        migrations.AddIndex(
            model_name='decisiontomada',
            index=models.Index(fields=['fue_acertada'], name='pragma_dash_fue_ace_6d69e9_idx'),
        ),
    ]
