# Generated by Django 5.2.8 on 2025-11-26 00:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pragma_dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalisisIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion_total', models.IntegerField(help_text='Puntuación global 0-100', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('nivel_general', models.CharField(help_text='Nivel general: Excelente, Bueno, Regular, Necesita mejorar, Crítico', max_length=50)),
                ('emoji_nivel', models.CharField(default='⚠️', help_text='Emoji representativo del nivel', max_length=10)),
                ('datos_json', models.JSONField(default=dict, help_text='Análisis completo en JSON desde N8N')),
                ('score_velocidad', models.DecimalField(decimal_places=1, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('score_precision', models.DecimalField(decimal_places=1, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('score_consistencia', models.DecimalField(decimal_places=1, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('score_manejo_estres', models.DecimalField(decimal_places=1, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('score_engagement', models.DecimalField(decimal_places=1, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('resumen_fortalezas', models.TextField(blank=True, help_text='Resumen de fortalezas identificadas')),
                ('resumen_areas_mejora', models.TextField(blank=True, help_text='Resumen de áreas a mejorar')),
                ('resumen_recomendaciones', models.TextField(blank=True, help_text='Recomendaciones personalizadas')),
                ('nivel_riesgo', models.CharField(choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto')], default='bajo', help_text='Nivel de riesgo detectado', max_length=20)),
                ('alertas_psicologicas', models.TextField(blank=True, help_text='Alertas psicológicas detectadas')),
                ('requiere_intervencion', models.BooleanField(default=False, help_text='Indica si requiere intervención profesional')),
                ('url_grafico_distribucion', models.URLField(blank=True, help_text='URL del gráfico de distribución')),
                ('url_grafico_radar', models.URLField(blank=True, help_text='URL del gráfico radar de competencias')),
                ('url_grafico_indicadores', models.URLField(blank=True, help_text='URL del gráfico de indicadores clave')),
                ('fecha_analisis', models.DateTimeField(auto_now_add=True, help_text='Fecha del análisis')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sesion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analisis_ia', to='pragma_dashboard.sesionsimulacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analisis_ia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Análisis IA',
                'verbose_name_plural': 'Análisis IA',
                'ordering': ['-fecha_analisis'],
                'indexes': [models.Index(fields=['usuario', '-fecha_analisis'], name='pragma_dash_usuario_2d3522_idx'), models.Index(fields=['nivel_riesgo'], name='pragma_dash_nivel_r_a2ffb2_idx'), models.Index(fields=['requiere_intervencion'], name='pragma_dash_requier_93d491_idx')],
            },
        ),
    ]
