# Generated by Django 5.2.8 on 2025-11-28 04:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pragma_dashboard', '0002_analisisia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analisisia',
            options={'ordering': ['-timestamp_analisis'], 'verbose_name': 'Análisis IA', 'verbose_name_plural': 'Análisis IA'},
        ),
        migrations.RemoveIndex(
            model_name='analisisia',
            name='pragma_dash_usuario_2d3522_idx',
        ),
        migrations.RemoveIndex(
            model_name='analisisia',
            name='pragma_dash_requier_93d491_idx',
        ),
        migrations.RemoveField(
            model_name='analisisia',
            name='datos_json',
        ),
        migrations.RemoveField(
            model_name='analisisia',
            name='emoji_nivel',
        ),
        migrations.RemoveField(
            model_name='analisisia',
            name='fecha_analisis',
        ),
        migrations.RemoveField(
            model_name='analisisia',
            name='nivel_general',
        ),
        migrations.RemoveField(
            model_name='analisisia',
            name='puntuacion_total',
        ),
        migrations.RemoveField(
            model_name='analisisia',
            name='resumen_areas_mejora',
        ),
        migrations.RemoveField(
            model_name='analisisia',
            name='resumen_fortalezas',
        ),
        migrations.RemoveField(
            model_name='analisisia',
            name='resumen_recomendaciones',
        ),
        migrations.RemoveField(
            model_name='analisisia',
            name='score_consistencia',
        ),
        migrations.RemoveField(
            model_name='analisisia',
            name='score_engagement',
        ),
        migrations.RemoveField(
            model_name='analisisia',
            name='score_manejo_estres',
        ),
        migrations.RemoveField(
            model_name='analisisia',
            name='score_precision',
        ),
        migrations.RemoveField(
            model_name='analisisia',
            name='score_velocidad',
        ),
        migrations.RemoveField(
            model_name='analisisia',
            name='url_grafico_distribucion',
        ),
        migrations.RemoveField(
            model_name='analisisia',
            name='url_grafico_indicadores',
        ),
        migrations.RemoveField(
            model_name='analisisia',
            name='url_grafico_radar',
        ),
        migrations.AddField(
            model_name='analisisia',
            name='analisis_detallado',
            field=models.JSONField(blank=True, default=dict, help_text='Análisis detallado (patrones, fortalezas, vulnerabilidades)'),
        ),
        migrations.AddField(
            model_name='analisisia',
            name='conclusiones_clinicas',
            field=models.TextField(blank=True, help_text='Conclusiones clínicas del análisis'),
        ),
        migrations.AddField(
            model_name='analisisia',
            name='datos_completos_groq',
            field=models.JSONField(blank=True, default=dict, help_text='Respuesta completa de Groq (backup)'),
        ),
        migrations.AddField(
            model_name='analisisia',
            name='graficos',
            field=models.JSONField(blank=True, default=dict, help_text='URLs de gráficos generados'),
        ),
        migrations.AddField(
            model_name='analisisia',
            name='indicadores_psicologicos',
            field=models.JSONField(blank=True, default=dict, help_text='Indicadores psicológicos y riesgo'),
        ),
        migrations.AddField(
            model_name='analisisia',
            name='mecanismos_afrontamiento',
            field=models.JSONField(blank=True, default=dict, help_text='Mecanismos de afrontamiento identificados'),
        ),
        migrations.AddField(
            model_name='analisisia',
            name='metadata_groq',
            field=models.JSONField(blank=True, default=dict, help_text='Metadata del análisis (modelo, tokens, timestamps)'),
        ),
        migrations.AddField(
            model_name='analisisia',
            name='perfil_psicoeducativo',
            field=models.JSONField(blank=True, default=dict, help_text='Perfil psicoeducativo del usuario'),
        ),
        migrations.AddField(
            model_name='analisisia',
            name='plan_intervencion',
            field=models.JSONField(blank=True, default=dict, help_text='Plan de intervención próximas sesiones'),
        ),
        migrations.AddField(
            model_name='analisisia',
            name='recomendaciones_especificas',
            field=models.JSONField(blank=True, default=list, help_text='Recomendaciones específicas de Groq'),
        ),
        migrations.AddField(
            model_name='analisisia',
            name='resumen_ejecutivo',
            field=models.TextField(blank=True, help_text='Resumen ejecutivo del análisis'),
        ),
        migrations.AddField(
            model_name='analisisia',
            name='savefile_id',
            field=models.IntegerField(db_index=True, default=0, help_text='ID del savefile (referencia externa)'),
        ),
        migrations.AddField(
            model_name='analisisia',
            name='timestamp_analisis',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Cuando Groq generó el análisis'),
        ),
        migrations.AddField(
            model_name='analisisia',
            name='timestamp_recibido',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Cuando llegó al backend'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analisisia',
            name='usuario_email',
            field=models.EmailField(blank=True, help_text='Email del usuario al momento del análisis', max_length=254),
        ),
        migrations.AddField(
            model_name='analisisia',
            name='usuario_nombre',
            field=models.CharField(blank=True, help_text='Nombre del usuario al momento del análisis', max_length=255),
        ),
        migrations.AlterField(
            model_name='analisisia',
            name='alertas_psicologicas',
            field=models.TextField(blank=True, help_text='Alertas psicológicas identificadas'),
        ),
        migrations.AlterField(
            model_name='analisisia',
            name='nivel_riesgo',
            field=models.CharField(choices=[('bajo', 'Bajo'), ('leve', 'Leve'), ('moderado', 'Moderado'), ('alto', 'Alto'), ('severo', 'Severo')], default='bajo', help_text='Nivel de riesgo psicológico general', max_length=20),
        ),
        migrations.AlterField(
            model_name='analisisia',
            name='requiere_intervencion',
            field=models.BooleanField(default=False, help_text='Si requiere intervención profesional inmediata'),
        ),
        migrations.AlterField(
            model_name='analisisia',
            name='sesion',
            field=models.OneToOneField(blank=True, help_text='Relación con sesión de simulación (opcional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analisis_ia', to='pragma_dashboard.sesionsimulacion'),
        ),
        migrations.AlterField(
            model_name='analisisia',
            name='usuario',
            field=models.ForeignKey(blank=True, help_text='Usuario propietario del análisis', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analisis_ia', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='analisisia',
            index=models.Index(fields=['savefile_id'], name='pragma_dash_savefil_c9b273_idx'),
        ),
        migrations.AddIndex(
            model_name='analisisia',
            index=models.Index(fields=['usuario'], name='pragma_dash_usuario_029d61_idx'),
        ),
        migrations.AddIndex(
            model_name='analisisia',
            index=models.Index(fields=['timestamp_analisis'], name='pragma_dash_timesta_7959b2_idx'),
        ),
    ]
